services:
  # PostgreSQL database service
  db:
    container_name: f1-database-service
    image: postgres:15
    restart: always
    env_file:
      - .env   # Load DB credentials from env file

    ports:
      - "${POSTGRES_PORT}:5432"  # Expose DB port to host
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist DB data
    healthcheck:
      # Check if Postgres is ready before starting dependent services
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 10

  # Backend FastAPI service
  backend:
    container_name: f1-backend-service
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be healthy before starting
    ports:
      - "8000:8000"  # API exposed on port 8000
    volumes:
      - ./backend/app:/app/app  # Mount source code for live reload during development
    restart: unless-stopped

  # Frontend React service for development mode
  frontend:
    container_name: f1-frontend-service
    build:
      context: .
      dockerfile: frontend/Dockerfile  # A Dockerfile that runs `npm run dev`
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

# Frontend React service for production mode -> NOT tested!
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"  # Serve frontend on standard HTTP port 80
#    depends_on:
#      - backend  # Ensure backend API is running
#    environment:
#      - VITE_HOST=0.0.0.0
#    restart: unless-stopped

volumes:
# Named volume to persist Postgres data outside container lifecycle
  pgdata:
